spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.137/1812
    username: root
    password: 2001
    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/1809a
mybatis:
  mapperLocations: classpath*:mybatis/*Dao.xml
  ##*typeAliasesPackage: com.jk.bean

  aop:
    auto: true

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    database: 1


